[package]
name = "mytinyrenderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "^0.4"

[dependencies]
png = "^0.17"

[[bench]]
name = "line_draw"
harness = false
